In [14]:
import pandas as pd
import requests
import time

parks = pd.read_csv('../data/processed/parks.csv')
parks.head()

,name,opened_at,area,facilities,plants,notes,district,address,department,phone,...,area_size,search_text,is_dog_forbidden,has_dog_park,has_parking,is_hilly,has_restroom,has_store,has_lawn,has_water
0,남산공원,1968.9.10,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,소나무 단풍 아카시아 상수리나무 등 191종 2881870주,남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...,중구,서울특별시 중구 삼일대로 231(예장동),중부공원여가센터,02-3783-5900,...,2896887.0,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,False,False,True,False,True,True,False,True
1,길동생태공원,1999.5.20,79258.7㎡,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대",소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본,매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. 공원을 깨끗하게 이용합...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),동부공원여가센 공원운영과,02-472-2770/ 02-489-2770,...,79258.7,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대 매주 월요일은...",False,False,True,False,False,False,False,False
2,서울대공원,1984.5.1,9132690m²,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,"엘레강스야자, 용설란, 파리지옥, 네펜데스, 장미 등",일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,과천시,경기도 과천시 대공원광장로 102,서울대공원 전략기획실,02-500-7033,...,9132690.0,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,False,False,False,False,False,False,False,False
3,서울숲,2005.6.18,480994㎡,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...,지하철 분당선 서울숲역 4번출구 도보로 약2분 2호선 뚝섬역 8번출구 도보로 약 1...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),동부여가센터 서울숲관리사무소,02-460-2905,...,480994.0,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,False,False,True,False,False,False,False,False
4,월드컵공원,2002.5.1,2284085㎡,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,NaN,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),서부공원여가센터,02-300-5501,...,2284085.0,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,False,False,True,True,True,True,True,False

In [ ]:
from dotenv import load_dotenv
import os

load_dotenv("../.env")

API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

lat = parks.loc[0, "lat"]
lon = parks.loc[0, "lon"]

print(lat, lon)

37.5501402 126.9903773

In [4]:
url = (
    "https://maps.googleapis.com/maps/api/elevation/json"
    f"?locations={lat},{lon}"
    f"&key={API_KEY}"
)

response = requests.get(url)

data = response.json()

print(data)

{'results': [{'elevation': 217.4936065673828, 'location': {'lat': 37.5501402, 'lng': 126.9903773}, 'resolution': 19.08790397644043}], 'status': 'OK'}

In [5]:
elevation = data["results"][0]["elevation"]

print(elevation)

217.4936065673828

In [16]:
parks.loc[0, "elevation"] = elevation

parks.head()

,name,opened_at,area,facilities,plants,notes,district,address,department,phone,...,search_text,is_dog_forbidden,has_dog_park,has_parking,is_hilly,has_restroom,has_store,has_lawn,has_water,elevation
0,남산공원,1968.9.10,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,소나무 단풍 아카시아 상수리나무 등 191종 2881870주,남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...,중구,서울특별시 중구 삼일대로 231(예장동),중부공원여가센터,02-3783-5900,...,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,False,False,True,False,True,True,False,True,217.493607
1,길동생태공원,1999.5.20,79258.7㎡,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대",소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본,매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. 공원을 깨끗하게 이용합...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),동부공원여가센 공원운영과,02-472-2770/ 02-489-2770,...,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대 매주 월요일은...",False,False,True,False,False,False,False,False,NaN
2,서울대공원,1984.5.1,9132690m²,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,"엘레강스야자, 용설란, 파리지옥, 네펜데스, 장미 등",일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,과천시,경기도 과천시 대공원광장로 102,서울대공원 전략기획실,02-500-7033,...,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,False,False,False,False,False,False,False,False,NaN
3,서울숲,2005.6.18,480994㎡,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...,지하철 분당선 서울숲역 4번출구 도보로 약2분 2호선 뚝섬역 8번출구 도보로 약 1...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),동부여가센터 서울숲관리사무소,02-460-2905,...,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,False,False,True,False,False,False,False,False,NaN
4,월드컵공원,2002.5.1,2284085㎡,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,NaN,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),서부공원여가센터,02-300-5501,...,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,False,False,True,True,True,True,True,False,NaN

In [8]:
len(parks)

133

In [17]:
batch = parks.iloc[100:133]

batch[["name", "lat", "lon"]]

parks[parks["lat"].isna() | parks["lon"].isna()]

Empty DataFrame
Columns: [name, opened_at, area, facilities, plants, notes, district, address, department, phone, image, lon, lat, area_size, search_text, is_dog_forbidden, has_dog_park, has_parking, is_hilly, has_restroom, has_store, has_lawn, has_water, elevation]
Index: []

[0 rows x 24 columns]

In [18]:
import requests

BATCH_SIZE = 50
elevations = []

for start in range(0, len(parks), BATCH_SIZE):

    batch = parks.iloc[start:start + BATCH_SIZE]

    locations = "|".join(
        batch.apply(
            lambda row: f"{row['lat']},{row['lon']}",
            axis=1
        )
    )

    url = (
        "https://maps.googleapis.com/maps/api/elevation/json"
        f"?locations={locations}"
        f"&key={API_KEY}"
    )

    response = requests.get(url, timeout=10)
    response.raise_for_status()

    data = response.json()

    if data["status"] != "OK":
        raise Exception(f"Elevation API Error: {data['status']}")

    elevations.extend(
        result["elevation"]
        for result in data["results"]
    )

    batch_number = start // BATCH_SIZE + 1
    print(
        f"Batch {batch_number} 완료 "
        f"({len(elevations)}/{len(parks)})"
    )

Batch 1 완료 (50/132)
Batch 2 완료 (100/132)
Batch 3 완료 (132/132)

In [19]:
parks["elevation"] = elevations

In [20]:
parks[["name", "elevation"]].head()

     name   elevation
0    남산공원  216.424164
1  길동생태공원   35.621777
2   서울대공원   80.991127
3     서울숲   11.545979
4   월드컵공원   83.976677

In [21]:
parks.to_csv(
    "../data/processed/parks_with_elevation.csv",
    index=False,
    encoding="utf-8-sig"
)