In [1]:
import pandas as pd
from pathlib import Path

In [2]:

df = pd.read_csv("../data/raw/서울시 주요 공원현황.csv", encoding="cp949")

print(f"공원 개수 : {len(df)}")

df.head()

공원 개수 : 133

,연번,공원명,공원개요,면적,개원일,주요시설,주요식물,안내도,오시는길,이용시참고사항,이미지,지역,공원주소,관리부서,전화번호,X좌표(GRS80TM),Y좌표(GRS80TM),X좌표(WGS84),Y좌표(WGS84),바로가기
0,1,남산공원,남산공원은 도심에 위치하여 서울시민에게 맑은 공기를 제공하는 자연휴식처이며 산책 꽃...,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,1968.9.10,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,소나무 단풍 아카시아 상수리나무 등 191종 2881870주,http://parks.seoul.go.kr/upload/seditorMulti/2...,명동역(남산케이블카 와룡묘 서울애니메이션센터 방면) 도보 명동역 3번출구 → 퍼시픽...,남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...,http://parks.seoul.go.kr/file/info/view.do?fId...,중구,서울특별시 중구 삼일대로 231(예장동),중부공원여가센터,02-3783-5900,198364.107,450395.554,126.990377,37.550140,http://parks.seoul.go.kr/template/sub/namsan.do
1,2,길동생태공원,길동생태공원은 생물의 서식처를 제공하고 종다양성을 증진시키며 자연생태계의 생물들을 ...,79258.7㎡,1999.5.20,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대",소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본,http://parks.seoul.go.kr/template/common/img/p...,지하철: 9호선 중앙보훈병원역 3번출구에서 시내버스 환승 5호선 강동역 4번출구에서...,매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. 공원을 깨끗하게 이용합...,http://parks.seoul.go.kr/file/info/view.do?fId...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),동부공원여가센 공원운영과,02-472-2770/ 02-489-2770,213554.120,448852.675,127.154779,37.540394,http://parks.seoul.go.kr/template/sub/gildong.do
2,3,서울대공원,서울대공원은 세계 각국의 야생동물들이 살아 숨 쉬는 서울동물원과 다양한 기후대의 식...,9132690m²,1984.5.1,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,"엘레강스야자, 용설란, 파리지옥, 네펜데스, 장미 등",https://grandpark.seoul.go.kr/conts/contsView/...,지하철 4호선 대공원역 하차(2번 출구) 도보 15분 정도 문의처 02)500-73...,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,http://parks.seoul.go.kr/file/info/view.do?fId...,과천시,경기도 과천시 대공원광장로 102,서울대공원 전략기획실,02-500-7033,200994.267,437163.981,127.019846,37.426449,http://grandpark.seoul.go.kr/
3,4,서울숲,서울숲은 한강과 중랑천이 만나고 한강-용산-남찬-청계천-서울숲-한강으로 연결되는 서...,480994㎡,2005.6.18,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...,http://parks.seoul.go.kr/template/common/img/p...,지하철: 분당선 서울숲역 4번출구에서 도보 약 2분 2호선 뚝섬역 8번출구에서 도보...,지하철 분당선 서울숲역 4번출구 도보로 약2분 2호선 뚝섬역 8번출구 도보로 약 1...,http://parks.seoul.go.kr/file/info/view.do?fId...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),동부여가센터 서울숲관리사무소,02-460-2905,203695.432,449290.726,127.041798,37.543072,http://parks.seoul.go.kr/template/sub/seoulfor...
4,5,월드컵공원,월드컵공원은 서울의 서쪽에 위치하여 1978년부터 1993년까지 15년간 서울시민이...,2284085㎡,2002.5.1,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,NaN,http://parks.seoul.go.kr/template/common/img/p...,지하철 6호선 월드컵경기장역 하차 → 1번 출구로 나온 후 직진 → 큰길(도로)이 ...,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,http://parks.seoul.go.kr/file/info/view.do?fId...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),서부공원여가센터,02-300-5501,190658.070,451598.831,126.878907,37.571805,http://parks.seoul.go.kr/template/sub/worldcup...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   연번            133 non-null    int64
 1   공원명           133 non-null    str
 2   공원개요          133 non-null    str
 3   면적            130 non-null    str
 4   개원일           126 non-null    str
 5   주요시설          128 non-null    str
 6   주요식물          93 non-null     str
 7   안내도           103 non-null    str
 8   오시는길          120 non-null    str
 9   이용시참고사항       122 non-null    str
 10  이미지           130 non-null    str
 11  지역            132 non-null    str
 12  공원주소          133 non-null    str
 13  관리부서          133 non-null    str
 14  전화번호          133 non-null    str
 15  X좌표(GRS80TM)  122 non-null    float64
 16  Y좌표(GRS80TM)  122 non-null    float64
 17  X좌표(WGS84)    132 non-null    float64
 18  Y좌표(WGS84)    132 non-null    float64
 19  바로가기          25 non-null     str
dtypes: float64(4), int64(1), str(15)
memory usage: 20.9 KB

In [4]:
df.columns

Index(['연번', '공원명', '공원개요', '면적', '개원일', '주요시설', '주요식물', '안내도', '오시는길',
       '이용시참고사항', '이미지', '지역', '공원주소', '관리부서', '전화번호', 'X좌표(GRS80TM)',
       'Y좌표(GRS80TM)', 'X좌표(WGS84)', 'Y좌표(WGS84)', '바로가기'],
      dtype='str')

In [5]:
# 결측치 확인
df.isnull().sum()

연번                0
공원명               0
공원개요              0
면적                3
개원일               7
주요시설              5
주요식물             40
안내도              30
오시는길             13
이용시참고사항          11
이미지               3
지역                1
공원주소              0
관리부서              0
전화번호              0
X좌표(GRS80TM)     11
Y좌표(GRS80TM)     11
X좌표(WGS84)        1
Y좌표(WGS84)        1
바로가기            108
dtype: int64

In [6]:
target_columns = [
    "공원명",
    "개원일",
    "면적",
    "주요시설",
    "주요식물",
    "이용시참고사항",
    "지역",
    "공원주소",
    "관리부서",
    "전화번호",
    "이미지",
    "X좌표(WGS84)",
    "Y좌표(WGS84)"
]

parks = df[target_columns].copy()

In [7]:
parks = parks.rename(columns={
    "공원명": "name",
    "개원일": "opened_at",
    "면적": "area",
    "주요시설": "facilities",
    "주요식물": "plants",
    "이용시참고사항": "notes",
    "지역": "district",
    "공원주소": "address",
    "관리부서": "department",
    "전화번호": "phone",
    "이미지": "image",
    "X좌표(WGS84)": "lon",
    "Y좌표(WGS84)": "lat",
})

parks.head()

,name,opened_at,area,facilities,plants,notes,district,address,department,phone,image,lon,lat
0,남산공원,1968.9.10,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,기반시설 : 광장 45950㎡ 도로 108530㎡ 산책로 6.7㎞ (북측:3.7㎞/...,소나무 단풍 아카시아 상수리나무 등 191종 2881870주,남산공원 차량통행 금지안내 2005년 5월 1일부터 남산공원에 일반승용차 택시 통행...,중구,서울특별시 중구 삼일대로 231(예장동),중부공원여가센터,02-3783-5900,http://parks.seoul.go.kr/file/info/view.do?fId...,126.990377,37.550140
1,길동생태공원,1999.5.20,79258.7㎡,"생태문화센터, 탐방객안내센터, 반딧불이 체험관, 목재데크, 조류관찰대",소나무 보리수 등 64종 31800주 산국 부들 등 138종 192800본,매주 월요일은 휴관입니다 사전예약 후 입장하실 수 있습니다. 공원을 깨끗하게 이용합...,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),동부공원여가센 공원운영과,02-472-2770/ 02-489-2770,http://parks.seoul.go.kr/file/info/view.do?fId...,127.154779,37.540394
2,서울대공원,1984.5.1,9132690m²,동물원 식물원 테마가든(장미원 어린이동물원 피크닉장) 치유숲 산림욕장 캠핑장 국립현...,"엘레강스야자, 용설란, 파리지옥, 네펜데스, 장미 등",일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,과천시,경기도 과천시 대공원광장로 102,서울대공원 전략기획실,02-500-7033,http://parks.seoul.go.kr/file/info/view.do?fId...,127.019846,37.426449
3,서울숲,2005.6.18,480994㎡,문화예술시설: 바닥분수 거울연못 군마상 야외무대 가족마당무대 생태시설: 꽃사슴방사장...,수 목 : 소나무 섬잣나무 계수나무 외 95종 415795주 식물원 : 선인장 등 ...,지하철 분당선 서울숲역 4번출구 도보로 약2분 2호선 뚝섬역 8번출구 도보로 약 1...,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),동부여가센터 서울숲관리사무소,02-460-2905,http://parks.seoul.go.kr/file/info/view.do?fId...,127.041798,37.543072
4,월드컵공원,2002.5.1,2284085㎡,평화의 공원 월드컵공원전시관(879㎡) 유니세프광장(2400㎡) 평화광장(5217㎡...,NaN,일반사항 공원을 깨끗하게 이용합니다. 대중교통을 이용해 주세요. 기념물 시설물 풀과...,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),서부공원여가센터,02-300-5501,http://parks.seoul.go.kr/file/info/view.do?fId...,126.878907,37.571805

In [8]:
text_columns = [
    "area",
    "facilities",
    "plants",
    "notes"
]

parks[text_columns] = parks[text_columns].fillna("")

parks = parks.dropna(subset=["lat", "lon"]).reset_index(drop=True)

In [9]:
parks["area_size"] = (
    parks["area"]
        .astype(str)
        .str.extract(r"([\d.]+)")
        .fillna(0)
        .astype(float)
)

parks[["area", "area_size"]].head()

                                           area  area_size
0  2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡  2896887.0
1                                      79258.7㎡    79258.7
2                                     9132690m²  9132690.0
3                                       480994㎡   480994.0
4                                      2284085㎡  2284085.0

In [10]:
parks["search_text"] = (
    parks["facilities"]
    + " "
    + parks["notes"]
    + " "
    + parks["plants"]
)

In [11]:
FORBIDDEN = [
    "애완견 금지",
    "반려견 금지",
    "반려동물 금지",
    "애완동물 금지",
    "출입 금지",
]

DOG_PARK = [
    "반려견 놀이터",
    "반려견놀이터",
    "반려견 운동장",
    "애완견 놀이터",
]

HILLY = [
    "등산로",
    "오르막",
    "계단",
    "임야",
    "자연 산책로",
    "산책 코스",
]

In [12]:
parks["is_dog_forbidden"] = parks["search_text"].apply(
    lambda text: any(keyword in text for keyword in FORBIDDEN)
)

parks["has_dog_park"] = parks["search_text"].apply(
    lambda text: any(keyword in text for keyword in DOG_PARK)
)

parks["has_parking"] = parks["search_text"].str.contains(
    "주차장",
    regex=False
)

parks["is_hilly"] = parks["search_text"].apply(
    lambda text: any(keyword in text for keyword in HILLY)
)

parks["has_restroom"] = parks["search_text"].str.contains(
    "화장실",
    regex=False
)

parks["has_store"] = parks["search_text"].str.contains(
    "매점",
    regex=False
)

parks["has_lawn"] = parks["search_text"].str.contains(
    "잔디",
    regex=False
)

parks["has_water"] = parks["search_text"].str.contains(
    "음수대",
    regex=False
)

In [13]:
parks[
    [
        "name",
        "area_size",
        "has_parking",
        "has_restroom",
        "has_lawn",
        "has_water",
        "has_dog_park",
        "is_dog_forbidden",
        "is_hilly",
    ]
].head(10)

,name,area_size,has_parking,has_restroom,has_lawn,has_water,has_dog_park,is_dog_forbidden,is_hilly
0,남산공원,2896887.0,True,True,False,True,False,False,False
1,길동생태공원,79258.7,True,False,False,False,False,False,False
2,서울대공원,9132690.0,False,False,False,False,False,False,False
3,서울숲,480994.0,True,False,False,False,False,False,False
4,월드컵공원,2284085.0,True,True,True,False,False,False,True
5,광화문시민열린마당,8948.1,True,False,False,False,False,False,False
6,진관근린공원(구파발폭포),7.0,False,False,False,False,False,False,False
7,중마루근린공원,6456.0,False,False,False,True,False,False,True
8,응봉공원 (대현산배수지공원),75570.0,False,True,True,True,False,False,False
9,매화근린공원,1980.4,False,False,False,False,False,False,False

In [14]:
print(f"전체 공원 : {len(parks)}")
print(f"반려동물 출입 금지 : {parks['is_dog_forbidden'].sum()}")
print(f"반려견 놀이터 : {parks['has_dog_park'].sum()}")
print(f"주차장 : {parks['has_parking'].sum()}")
print(f"화장실 : {parks['has_restroom'].sum()}")
print(f"매점 : {parks['has_store'].sum()}")
print(f"잔디 : {parks['has_lawn'].sum()}")
print(f"음수대 : {parks['has_water'].sum()}")
print(f"경사 예상 : {parks['is_hilly'].sum()}")

전체 공원 : 132
반려동물 출입 금지 : 0
반려견 놀이터 : 0
주차장 : 13
화장실 : 36
매점 : 8
잔디 : 23
음수대 : 21
경사 예상 : 13

In [15]:
from pathlib import Path

Path("../data/processed").mkdir(parents=True, exist_ok=True)

parks.to_csv(
    "../data/processed/parks.csv",
    index=False,
    encoding="utf-8-sig"
)